name: "CI"

env:
  TS_PROFILE: "ci"

on:
  pull_request:
    branches:
      - "main"
      - "develop"
  push:
    branches:
      - "main"
      - "develop"

jobs:
  check_pull_requests:
    runs-on: ubuntu-latest
    name: Check linked issues
    steps:
      - uses: nearform/github-action-check-linked-issues@v1
        id: check-linked-issues
        with:
          exclude-branches: "release/**, dependabot/**"

  ci:
    name: Lint & Test
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install the Node.js dependencies"
        run: "yarn install --immutable"

      - name: "Lint"
        run: "yarn lint"

      - name: "Add lint summary"
        run: |
          echo "## Lint" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
